/** Central business information for WAGI - STATIONARIES. */
export const STORE = {
  name: "WAGI - STATIONARIES",
  shortName: "WAGI",
  initials: "WS",
  tagline: "Quality stationery, delivered across Kenya",
  email: "wagistationaries2026@gmail.com",
  phone: "0705734326",
  phoneIntl: "+254705734326",
  whatsapp: "254705734326",
  mpesaPhone: "0705734326",
  addressLine: "Latema Road",
  city: "Nairobi",
  country: "Kenya",
  fullAddress: "Latema Road, Nairobi, Kenya",
  hours: "Monday – Saturday, 8:00 AM – 6:00 PM",
  mapsQuery: "Latema Road, Nairobi, Kenya",
  currency: "KES",
} as const;

export const KENYAN_COUNTIES = [
  "Nairobi",
  "Kiambu",
  "Machakos",
  "Kajiado",
  "Nakuru",
  "Mombasa",
  "Kisumu",
  "Uasin Gishu",
  "Nyeri",
  "Meru",
  "Kakamega",
  "Kilifi",
  "Bungoma",
  "Kericho",
  "Laikipia",
  "Trans Nzoia",
  "Muranga",
  "Embu",
  "Narok",
  "Bomet",
  "Migori",
  "Homa Bay",
  "Siaya",
  "Busia",
  "Vihiga",
  "Nandi",
  "Baringo",
  "Nyandarua",
  "Kirinyaga",
  "Kitui",
  "Makueni",
  "Taita Taveta",
  "Kwale",
  "Lamu",
  "Tana River",
  "Garissa",
  "Wajir",
  "Mandera",
  "Marsabit",
  "Isiolo",
  "Samburu",
  "Turkana",
  "West Pokot",
  "Elgeyo Marakwet",
  "Nyamira",
  "Kisii",
  "Tharaka Nithi",
] as const;

export const ORDER_STATUS_FLOW = [
  "pending",
  "paid",
  "processing",
  "packed",
  "out_for_delivery",
  "delivered",
] as const;

export const ORDER_STATUS_LABELS: Record<string, string> = {
  pending: "Pending",
  paid: "Paid",
  processing: "Processing",
  packed: "Packed",
  out_for_delivery: "Out for delivery",
  delivered: "Delivered",
  cancelled: "Cancelled",
  returned: "Returned",
};

export const PAYMENT_STATUS_LABELS: Record<string, string> = {
  unpaid: "Unpaid",
  pending: "Awaiting payment",
  paid: "Paid",
  failed: "Failed",
  refunded: "Refunded",
};
