
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.update_updated_at_column() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.refresh_product_rating() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.apply_order_item_stock() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.restore_stock_on_cancel() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.log_order_status_change() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) FROM anon;

INSERT INTO public.categories (name, slug, description, icon, sort_order) VALUES
 ('Whiteboard Supplies','whiteboard-supplies','Markers, inks and dusters for classrooms, offices and boardrooms.','PenLine',1),
 ('Scientific Calculators','scientific-calculators','Genuine Casio scientific calculators for school, college and professional use.','Calculator',2),
 ('Mathematical Tables','mathematical-tables','KLB mathematical tables approved for Kenyan schools and national exams.','Table',3),
 ('Mathematical Sets','mathematical-sets','Geometry sets, set squares, drawing sets and gift sets.','Compass',4),
 ('Pens','pens','Calligraphy, fountain, felt tip and erasable pens.','Pen',5),
 ('Art Supplies','art-supplies','Brushes and materials for artists and design students.','Brush',6);

INSERT INTO public.products (name, slug, brand, description, specifications, category_id, subcategory, sku, barcode, price, discount_price, stock_quantity, is_featured, is_new_arrival, is_flash_sale)
SELECT v.name, v.slug, v.brand, v.description, v.specs::jsonb, c.id, v.subcategory, v.sku, v.barcode, v.price, v.discount_price, v.stock, v.featured, v.new_arrival, v.flash
FROM (VALUES
 ('K-Max Whiteboard Marker - Transparent','k-max-whiteboard-marker-transparent','K-Max','Refillable transparent-barrel K-Max whiteboard marker with a chisel tip and low-odour ink. The see-through barrel lets you check the remaining ink at a glance, and the marker can be topped up with whiteboard ink instead of being thrown away.','{"Tip":"Chisel","Barrel":"Transparent refillable","Ink":"Low odour, dry erase","Sold as":"Single piece"}','whiteboard-supplies','K-Max Whiteboard Markers','WS-WB-KMAX-TR',NULL,80,65,240,true,false,true),
 ('K-Max Whiteboard Marker - Coloured (Set of 4)','k-max-whiteboard-marker-coloured','K-Max','Set of four K-Max whiteboard markers in black, blue, red and green. Chisel tip for both thick and thin strokes, refillable barrel and quick-drying dry erase ink that wipes clean without ghosting.','{"Tip":"Chisel","Colours":"Black, Blue, Red, Green","Barrel":"Refillable","Sold as":"Pack of 4"}','whiteboard-supplies','K-Max Whiteboard Markers','WS-WB-KMAX-CL',NULL,300,260,150,true,false,true),
 ('Gxine Whiteboard Ink - Big','gxine-whiteboard-ink-big','Gxine','Large bottle of Gxine whiteboard refill ink. Economical for schools and offices that refill markers in bulk. Fast drying, erases cleanly from all melamine and glass whiteboards.','{"Volume":"Large bottle","Type":"Dry erase refill ink","Colours":"Black, Blue, Red, Green","Use":"Refilling whiteboard markers"}','whiteboard-supplies','Gxine Whiteboard Ink','WS-WB-GX-BIG',NULL,350,NULL,90,false,false,false),
 ('Gxine Whiteboard Ink - Small','gxine-whiteboard-ink-small','Gxine','Small bottle of Gxine whiteboard refill ink, ideal for individual teachers and small offices. Refills a standard marker several times.','{"Volume":"Small bottle","Type":"Dry erase refill ink","Colours":"Black, Blue, Red, Green"}','whiteboard-supplies','Gxine Whiteboard Ink','WS-WB-GX-SML',NULL,180,150,130,false,false,false),
 ('Kero Whiteboard Marker','kero-whiteboard-marker','Kero','Kero whiteboard marker with a durable chisel tip and smooth, high-contrast ink. A dependable everyday marker for classrooms and meeting rooms.','{"Tip":"Chisel","Ink":"Dry erase","Colours":"Black, Blue, Red","Sold as":"Single piece"}','whiteboard-supplies','Kero Whiteboard Markers','WS-WB-KERO-01',NULL,70,NULL,300,false,true,false),
 ('Whiteboard Ink Refill Bottle','whiteboard-ink-refill','WAGI','General purpose whiteboard refill ink for topping up refillable markers. Bright pigment, quick drying and easy to erase.','{"Type":"Dry erase refill ink","Colours":"Black, Blue, Red, Green"}','whiteboard-supplies','Whiteboard Ink','WS-WB-INK-01',NULL,200,NULL,110,false,false,false),
 ('Whiteboard Duster','whiteboard-duster','WAGI','Magnetic-backed whiteboard duster with a soft felt pad. Wipes boards clean without smearing and sticks to the board when not in use.','{"Pad":"Soft felt","Backing":"Magnetic","Use":"Melamine, glass and porcelain boards"}','whiteboard-supplies','Whiteboard Dusters','WS-WB-DUST-01',NULL,150,120,180,true,false,false),
 ('Casio FX-991ES Plus Scientific Calculator','casio-fx-991es-plus','Casio','Casio FX-991ES Plus with Natural Textbook Display, 417 functions, solar plus battery power. The standard choice for engineering, university and advanced secondary school work.','{"Functions":"417","Display":"Natural Textbook Display","Power":"Solar + battery","Exam use":"Non-programmable"}','scientific-calculators','Casio FX-991ES Plus','WS-CAL-991ESP',NULL,2200,1950,60,true,true,true),
 ('Casio FX-991ES Scientific Calculator','casio-fx-991es','Casio','Casio FX-991ES scientific calculator with Natural Display, equation solving, matrix and vector calculations. Dual solar and battery powered.','{"Display":"Natural Display","Power":"Solar + battery","Exam use":"Non-programmable"}','scientific-calculators','Casio FX-991ES','WS-CAL-991ES',NULL,2000,NULL,45,false,false,false),
 ('Casio FX-82MS Scientific Calculator','casio-fx-82ms','Casio','Casio FX-82MS two-line display scientific calculator with 240 functions. The most widely used calculator in Kenyan secondary schools.','{"Functions":"240","Display":"2-line","Power":"Battery","Exam use":"Non-programmable"}','scientific-calculators','Casio FX-82MS','WS-CAL-82MS',NULL,1300,1150,120,true,false,true),
 ('Casio FX-82ES Scientific Calculator','casio-fx-82es','Casio','Casio FX-82ES with Natural Textbook Display showing fractions, roots and powers exactly as they appear in textbooks. Ideal for KCSE candidates.','{"Display":"Natural Textbook Display","Power":"Battery","Exam use":"Non-programmable"}','scientific-calculators','Casio FX-82ES','WS-CAL-82ES',NULL,1450,NULL,80,false,false,false),
 ('Casio FX-100MS Scientific Calculator','casio-fx-100ms','Casio','Casio FX-100MS with 300 functions and a two-line display, covering statistics, complex numbers and base-n calculations for college level study.','{"Functions":"300","Display":"2-line","Power":"Solar + battery"}','scientific-calculators','Casio FX-100MS','WS-CAL-100MS',NULL,1800,NULL,50,false,false,false),
 ('Casio FX-570ES Scientific Calculator','casio-fx-570es','Casio','Casio FX-570ES with Natural Textbook Display and 403 functions including integration, differentiation and matrix operations.','{"Functions":"403","Display":"Natural Textbook Display","Power":"Battery"}','scientific-calculators','Casio FX-570ES','WS-CAL-570ES',NULL,1950,1800,40,false,true,false),
 ('Casio FX-570MS Scientific Calculator','casio-fx-570ms','Casio','Casio FX-570MS two-line scientific calculator with 401 functions, suited to advanced secondary school and technical college mathematics.','{"Functions":"401","Display":"2-line","Power":"Battery"}','scientific-calculators','Casio FX-570MS','WS-CAL-570MS',NULL,1700,NULL,55,false,false,false),
 ('Mathematical Tables - 6th Edition','mathematical-tables-6th-edition','KLB','Four-figure mathematical tables, 6th edition, containing logarithms, squares, square roots, reciprocals and trigonometric tables used in Kenyan secondary schools.','{"Edition":"6th","Pages":"Four-figure tables","Binding":"Paperback","Use":"Secondary school and KCSE"}','mathematical-tables','6th Edition','WS-MT-6ED',NULL,120,100,200,false,false,false),
 ('Mathematical Tables - 7th Edition','mathematical-tables-7th-edition','KLB','Four-figure mathematical tables, 7th edition — the current revised edition approved for use in Kenyan schools and national examinations.','{"Edition":"7th","Pages":"Four-figure tables","Binding":"Paperback","Use":"Secondary school and KCSE"}','mathematical-tables','7th Edition','WS-MT-7ED',NULL,150,130,260,true,true,false),
 ('Set Square Pair','set-square-pair','WAGI','Pair of clear acrylic set squares (45 degrees and 30/60 degrees) with bevelled edges and clear graduations for accurate technical drawing.','{"Contents":"45° and 30/60° squares","Material":"Clear acrylic","Use":"Technical drawing and geometry"}','mathematical-sets','Set Square','WS-MS-SQ-01',NULL,120,NULL,140,false,false,false),
 ('Geometry Drawing Set','geometry-drawing-set','WAGI','Complete geometry drawing set in a metal tin: compass, divider, protractor, set squares, 15cm ruler, pencil, sharpener and eraser. Everything a student needs for mathematics and technical drawing.','{"Contents":"Compass, divider, protractor, set squares, ruler, pencil, sharpener, eraser","Case":"Metal tin","Use":"Secondary school and college"}','mathematical-sets','Drawing Set','WS-MS-DS-01',NULL,350,299,170,true,false,true),
 ('Mathematical Gift Set','mathematical-gift-set','WAGI','Premium mathematical instruments presented in a gift box — a thoughtful present for students starting secondary school or joining college.','{"Contents":"Precision compass set, protractor, set squares, ruler","Case":"Gift presentation box"}','mathematical-sets','Gift Sets','WS-MS-GS-01',NULL,750,650,60,false,true,false),
 ('Calligraphy Pen Set','calligraphy-pen-set','WAGI','Calligraphy pen set with interchangeable italic nibs and ink cartridges for lettering, certificates and hand-drawn signage.','{"Nibs":"Interchangeable italic nibs","Ink":"Cartridge fed","Sold as":"Set"}','pens','Calligraphy Pens','WS-PEN-CAL-01',NULL,850,750,45,false,false,false),
 ('Fountain Pen','fountain-pen','WAGI','Classic fountain pen with a smooth stainless steel nib and a refillable converter or cartridge system. Balanced metal barrel for comfortable long-form writing.','{"Nib":"Stainless steel, fine","Filling":"Cartridge or converter","Barrel":"Metal"}','pens','Fountain Pens','WS-PEN-FTN-01',NULL,600,NULL,70,true,false,false),
 ('Felt Tip Pen Set (10 Colours)','felt-tip-pen-set','WAGI','Set of ten fine felt tip pens in assorted colours. Water based ink for notes, journalling, colour coding and classroom charts.','{"Tip":"Fine felt","Colours":"10 assorted","Ink":"Water based"}','pens','Felt Tip Pens','WS-PEN-FLT-10',NULL,450,390,95,false,false,true),
 ('Erasable Pen (Pack of 3)','erasable-pen-pack','WAGI','Erasable gel pens that rub out cleanly with the tip cap and rewrite without damaging the paper. Perfect for revision notes and planners.','{"Ink":"Erasable gel, 0.7mm","Colours":"Blue, Black, Red","Sold as":"Pack of 3"}','pens','Erasable Pens','WS-PEN-ERS-03',NULL,300,250,160,false,true,false),
 ('Artist Brush Set','artist-brush-set','WAGI','Set of artist brushes in assorted round and flat sizes with seamless ferrules and lacquered handles. Suitable for watercolour, acrylic and poster paint.','{"Shapes":"Round and flat","Sizes":"Assorted","Handles":"Lacquered wood","Use":"Watercolour, acrylic, poster paint"}','art-supplies','Art Brushes','WS-ART-BR-SET',NULL,550,480,75,true,false,false)
) AS v(name, slug, brand, description, specs, cat_slug, subcategory, sku, barcode, price, discount_price, stock, featured, new_arrival, flash)
JOIN public.categories c ON c.slug = v.cat_slug;

INSERT INTO public.coupons (code, description, discount_type, discount_value, min_order_amount, is_active)
VALUES ('WAGI10','10% off your order','percent',10,1000,true),
       ('BACKTOSCHOOL','KES 200 off orders above KES 3,000','fixed',200,3000,true);
